local Highlight = require("gruber-darker.highlight")
local c = require("gruber-darker.palette")
local opts = require("gruber-darker.config").get_opts()

---@type HighlightsProvider
local M = {
	highlights = {},
}

function M.setup()
	for _, value in pairs(M.highlights) do
		value:setup()
	end
end

-- bufferline.nvim

M.highlights.bufferline_fill = Highlight.new("BufferLineFill", { bg = c["bg-1"] })
M.highlights.bufferline_background = Highlight.new("BufferLineBackground", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_buffer_selected = Highlight.new("BufferLineBufferSelected", { fg = c["fg+2"], bg = c.bg, bold = opts.bold })
M.highlights.bufferline_buffer_visible = Highlight.new("BufferLineBufferVisible", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_separator = Highlight.new("BufferLineSeparator", { fg = c["bg-1"], bg = c["bg+1"] })
M.highlights.bufferline_separator_selected = Highlight.new("BufferLineSeparatorSelected", { fg = c["bg-1"], bg = c.bg })
M.highlights.bufferline_separator_visible = Highlight.new("BufferLineSeparatorVisible", { fg = c["bg-1"], bg = c["bg+1"] })
M.highlights.bufferline_indicator_selected = Highlight.new("BufferLineIndicatorSelected", { fg = c.yellow, bg = c.bg })
M.highlights.bufferline_indicator_visible = Highlight.new("BufferLineIndicatorVisible", { fg = c["bg+1"], bg = c["bg+1"] })
M.highlights.bufferline_modified = Highlight.new("BufferLineModified", { fg = c.green, bg = c["bg+1"] })
M.highlights.bufferline_modified_selected = Highlight.new("BufferLineModifiedSelected", { fg = c.green, bg = c.bg })
M.highlights.bufferline_modified_visible = Highlight.new("BufferLineModifiedVisible", { fg = c.green, bg = c["bg+1"] })
M.highlights.bufferline_error = Highlight.new("BufferLineError", { fg = c["red-1"], bg = c["bg+1"] })
M.highlights.bufferline_error_selected = Highlight.new("BufferLineErrorSelected", { fg = c.red, bg = c.bg })
M.highlights.bufferline_error_visible = Highlight.new("BufferLineErrorVisible", { fg = c["red-1"], bg = c["bg+1"] })
M.highlights.bufferline_error_diagnostic = Highlight.new("BufferLineErrorDiagnostic", { fg = c["red-1"], bg = c["bg+1"] })
M.highlights.bufferline_error_diagnostic_selected = Highlight.new("BufferLineErrorDiagnosticSelected", { fg = c.red, bg = c.bg })
M.highlights.bufferline_warning = Highlight.new("BufferLineWarning", { fg = c.brown, bg = c["bg+1"] })
M.highlights.bufferline_warning_selected = Highlight.new("BufferLineWarningSelected", { fg = c.yellow, bg = c.bg })
M.highlights.bufferline_warning_visible = Highlight.new("BufferLineWarningVisible", { fg = c.brown, bg = c["bg+1"] })
M.highlights.bufferline_warning_diagnostic = Highlight.new("BufferLineWarningDiagnostic", { fg = c.brown, bg = c["bg+1"] })
M.highlights.bufferline_warning_diagnostic_selected = Highlight.new("BufferLineWarningDiagnosticSelected", { fg = c.yellow, bg = c.bg })
M.highlights.bufferline_hint = Highlight.new("BufferLineHint", { fg = c["niagara-1"], bg = c["bg+1"] })
M.highlights.bufferline_hint_selected = Highlight.new("BufferLineHintSelected", { fg = c.niagara, bg = c.bg })
M.highlights.bufferline_hint_diagnostic = Highlight.new("BufferLineHintDiagnostic", { fg = c["niagara-1"], bg = c["bg+1"] })
M.highlights.bufferline_hint_diagnostic_selected = Highlight.new("BufferLineHintDiagnosticSelected", { fg = c.niagara, bg = c.bg })
M.highlights.bufferline_info = Highlight.new("BufferLineInfo", { fg = c["niagara-1"], bg = c["bg+1"] })
M.highlights.bufferline_info_selected = Highlight.new("BufferLineInfoSelected", { fg = c.green, bg = c.bg })
M.highlights.bufferline_info_diagnostic = Highlight.new("BufferLineInfoDiagnostic", { fg = c["niagara-1"], bg = c["bg+1"] })
M.highlights.bufferline_info_diagnostic_selected = Highlight.new("BufferLineInfoDiagnosticSelected", { fg = c.green, bg = c.bg })
M.highlights.bufferline_pick = Highlight.new("BufferLinePick", { fg = c["red+1"], bg = c["bg+1"], bold = opts.bold })
M.highlights.bufferline_pick_selected = Highlight.new("BufferLinePickSelected", { fg = c["red+1"], bg = c.bg, bold = opts.bold })
M.highlights.bufferline_pick_visible = Highlight.new("BufferLinePickVisible", { fg = c["red+1"], bg = c["bg+1"], bold = opts.bold })
M.highlights.bufferline_tab = Highlight.new("BufferLineTab", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_tab_selected = Highlight.new("BufferLineTabSelected", { fg = c["fg+2"], bg = c.bg, bold = opts.bold })
M.highlights.bufferline_tab_close = Highlight.new("BufferLineTabClose", { fg = c.red, bg = c["bg+1"] })
M.highlights.bufferline_tab_separator = Highlight.new("BufferLineTabSeparator", { fg = c["bg-1"], bg = c["bg+1"] })
M.highlights.bufferline_tab_separator_selected = Highlight.new("BufferLineTabSeparatorSelected", { fg = c["bg-1"], bg = c.bg })
M.highlights.bufferline_close_button = Highlight.new("BufferLineCloseButton", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_close_button_selected = Highlight.new("BufferLineCloseButtonSelected", { fg = c.red, bg = c.bg })
M.highlights.bufferline_close_button_visible = Highlight.new("BufferLineCloseButtonVisible", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_numbers = Highlight.new("BufferLineNumbers", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_numbers_selected = Highlight.new("BufferLineNumbersSelected", { fg = c.yellow, bg = c.bg, bold = opts.bold })
M.highlights.bufferline_numbers_visible = Highlight.new("BufferLineNumbersVisible", { fg = c.quartz, bg = c["bg+1"] })
M.highlights.bufferline_duplicate = Highlight.new("BufferLineDuplicate", { fg = c["niagara-1"], bg = c["bg+1"], italic = true })
M.highlights.bufferline_duplicate_selected = Highlight.new("BufferLineDuplicateSelected", { fg = c.niagara, bg = c.bg, italic = true })
M.highlights.bufferline_duplicate_visible = Highlight.new("BufferLineDuplicateVisible", { fg = c["niagara-1"], bg = c["bg+1"], italic = true })
M.highlights.bufferline_group_label = Highlight.new("BufferLineGroupLabel", { fg = c.black, bg = c.yellow })
M.highlights.bufferline_group_separator = Highlight.new("BufferLineGroupSeparator", { fg = c.yellow, bg = c["bg+1"] })
M.highlights.bufferline_offset_separator = Highlight.new("BufferLineOffsetSeparator", { fg = c["bg+4"], bg = c["bg+1"] })

-- neo-tree.nvim

M.highlights.neo_tree_normal = Highlight.new("NeoTreeNormal", { fg = c.fg, bg = c["bg-1"] })
M.highlights.neo_tree_normal_nc = Highlight.new("NeoTreeNormalNC", { fg = c.fg, bg = c["bg-1"] })
M.highlights.neo_tree_end_of_buffer = Highlight.new("NeoTreeEndOfBuffer", { fg = c["bg-1"], bg = c["bg-1"] })
M.highlights.neo_tree_root_name = Highlight.new("NeoTreeRootName", { fg = c.yellow, bold = opts.bold })
M.highlights.neo_tree_directory_icon = Highlight.new("NeoTreeDirectoryIcon", { fg = c.brown })
M.highlights.neo_tree_directory_name = Highlight.new("NeoTreeDirectoryName", { fg = c.niagara })
M.highlights.neo_tree_file_name = Highlight.new("NeoTreeFileName", { fg = c.fg })
M.highlights.neo_tree_file_name_opened = Highlight.new("NeoTreeFileNameOpened", { fg = c["fg+2"] })
M.highlights.neo_tree_symbolic_link_target = Highlight.new("NeoTreeSymbolicLinkTarget", { fg = c.quartz, underline = true })
M.highlights.neo_tree_indent_marker = Highlight.new("NeoTreeIndentMarker", { fg = c["niagara-2"] })
M.highlights.neo_tree_expander = Highlight.new("NeoTreeExpander", { fg = c.brown })
M.highlights.neo_tree_cursor_line = Highlight.new("NeoTreeCursorLine", { bg = c["bg+1"] })
M.highlights.neo_tree_dim_text = Highlight.new("NeoTreeDimText", { fg = c["niagara-1"] })
M.highlights.neo_tree_dotfile = Highlight.new("NeoTreeDotfile", { fg = c["niagara-1"] })
M.highlights.neo_tree_hidden = Highlight.new("NeoTreeHidden", { fg = c["niagara-1"], italic = true })
M.highlights.neo_tree_win_separator = Highlight.new("NeoTreeWinSeparator", { fg = c["bg+4"], bg = c["bg-1"] })
M.highlights.neo_tree_status_line = Highlight.new("NeoTreeStatusLine", { fg = c.quartz, bg = c["bg-1"] })
M.highlights.neo_tree_status_line_nc = Highlight.new("NeoTreeStatusLineNC", { fg = c["niagara-1"], bg = c["bg-1"] })
M.highlights.neo_tree_sign_column = Highlight.new("NeoTreeSignColumn", { fg = c["bg-1"], bg = c["bg-1"] })
M.highlights.neo_tree_filter_term = Highlight.new("NeoTreeFilterTerm", { fg = c.yellow, bold = opts.bold })
M.highlights.neo_tree_git_added = Highlight.new("NeoTreeGitAdded", { fg = c.green })
M.highlights.neo_tree_git_conflict = Highlight.new("NeoTreeGitConflict", { fg = c.red, bold = opts.bold })
M.highlights.neo_tree_git_deleted = Highlight.new("NeoTreeGitDeleted", { fg = c["red+1"] })
M.highlights.neo_tree_git_ignored = Highlight.new("NeoTreeGitIgnored", { fg = c["niagara-1"] })
M.highlights.neo_tree_git_modified = Highlight.new("NeoTreeGitModified", { fg = c.yellow })
M.highlights.neo_tree_git_unstaged = Highlight.new("NeoTreeGitUnstaged", { fg = c.brown })
M.highlights.neo_tree_git_untracked = Highlight.new("NeoTreeGitUntracked", { fg = c.green })
M.highlights.neo_tree_git_staged = Highlight.new("NeoTreeGitStaged", { fg = c.green })
M.highlights.neo_tree_title_bar = Highlight.new("NeoTreeTitleBar", { fg = c.black, bg = c.yellow })
M.highlights.neo_tree_tab_active = Highlight.new("NeoTreeTabActive", { fg = c["fg+2"], bg = c.bg, bold = opts.bold })
M.highlights.neo_tree_tab_inactive = Highlight.new("NeoTreeTabInactive", { fg = c.quartz, bg = c["bg-1"] })
M.highlights.neo_tree_tab_separator_active = Highlight.new("NeoTreeTabSeparatorActive", { fg = c["bg-1"], bg = c.bg })
M.highlights.neo_tree_tab_separator_inactive = Highlight.new("NeoTreeTabSeparatorInactive", { fg = c["bg-1"], bg = c["bg-1"] })
M.highlights.neo_tree_float_border = Highlight.new("NeoTreeFloatBorder", { fg = c.niagara })
M.highlights.neo_tree_float_title = Highlight.new("NeoTreeFloatTitle", { fg = c.white, bold = opts.bold })
M.highlights.neo_tree_vert_split = Highlight.new("NeoTreeVertSplit", { fg = c["bg+4"], bg = c["bg-1"] })

-- which-key.nvim

M.highlights.which_key = Highlight.new("WhichKey", { fg = c.yellow, bold = opts.bold })
M.highlights.which_key_group = Highlight.new("WhichKeyGroup", { fg = c.niagara })
M.highlights.which_key_desc = Highlight.new("WhichKeyDesc", { fg = c.fg })
M.highlights.which_key_value = Highlight.new("WhichKeyValue", { fg = c.quartz })
M.highlights.which_key_separator = Highlight.new("WhichKeySeparator", { fg = c.brown })
M.highlights.which_key_float = Highlight.new("WhichKeyFloat", { fg = c.fg, bg = c["bg+1"] })
M.highlights.which_key_border = Highlight.new("WhichKeyBorder", { fg = c.niagara })
M.highlights.which_key_title = Highlight.new("WhichKeyTitle", { fg = c.white, bold = opts.bold })
M.highlights.which_key_normal = Highlight.new("WhichKeyNormal", { fg = c.fg, bg = c["bg+1"] })

-- mason.nvim

M.highlights.mason_normal = Highlight.new("MasonNormal", { fg = c.fg, bg = c["bg+1"] })
M.highlights.mason_header = Highlight.new("MasonHeader", { fg = c.black, bg = c.yellow, bold = opts.bold })
M.highlights.mason_header_secondary = Highlight.new("MasonHeaderSecondary", { fg = c.black, bg = c.niagara, bold = opts.bold })
M.highlights.mason_highlight = Highlight.new("MasonHighlight", { fg = c.niagara })
M.highlights.mason_highlight_block = Highlight.new("MasonHighlightBlock", { fg = c.black, bg = c.niagara })
M.highlights.mason_highlight_block_bold = Highlight.new("MasonHighlightBlockBold", { fg = c.black, bg = c.niagara, bold = opts.bold })
M.highlights.mason_highlight_secondary = Highlight.new("MasonHighlightSecondary", { fg = c.yellow })
M.highlights.mason_highlight_block_secondary = Highlight.new("MasonHighlightBlockSecondary", { fg = c.black, bg = c.yellow })
M.highlights.mason_highlight_block_bold_secondary = Highlight.new("MasonHighlightBlockBoldSecondary", { fg = c.black, bg = c.yellow, bold = opts.bold })
M.highlights.mason_muted = Highlight.new("MasonMuted", { fg = c["niagara-1"] })
M.highlights.mason_muted_block = Highlight.new("MasonMutedBlock", { fg = c.fg, bg = c["bg+2"] })
M.highlights.mason_muted_block_bold = Highlight.new("MasonMutedBlockBold", { fg = c.fg, bg = c["bg+2"], bold = opts.bold })
M.highlights.mason_error = Highlight.new("MasonError", { fg = c.red, bold = opts.bold })

return M
